package com.pengshengtj.dao;

import com.pengshengtj.popj.Certif;
import java.util.List;

public interface CertifMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificates
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificates
     *
     * @mbg.generated
     */
    int insert(Certif record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificates
     *
     * @mbg.generated
     */
    Certif selectByPrimaryKey(Integer cerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificates
     *
     * @mbg.generated
     */
    List<Certif> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table certificates
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Certif record);
}