package com.pengshengtj.dao;

import com.pengshengtj.popj.Insurance;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InsuranceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer insid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated
     */
    int insert(Insurance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated
     */
    Insurance selectByPrimaryKey(Integer insid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated
     */
    List<Insurance> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table insurance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Insurance record);

    Insurance selectByVid(@Param("vid") Integer vid);

    int updateByVid(Insurance insurance);

    int deleteByVid(@Param("vid") Integer vid);
}