package com.pengshengtj.dao;

import com.pengshengtj.popj.Owner;
import com.pengshengtj.popj.Vehice;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownertable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ownid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownertable
     *
     * @mbg.generated
     */
    int insert(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownertable
     *
     * @mbg.generated
     */
    Owner selectByPrimaryKey(Integer ownid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownertable
     *
     * @mbg.generated
     */
    List<Owner> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ownertable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Owner record);

    List<Owner> selectByOweName(@Param("ownname") String ownname);

    Owner selectByVid(@Param("vid") Integer vid);

    List<Owner> selectByOweNameAndTime(@Param("ownname") String ownname,@Param("ownphone") String ownphone,@Param("vid") List<Integer> vid);

    List<Owner> selectByPhone();

    List<Owner> selectOwnerByVid(@Param("vid") List<Integer> vid );

    int insertOwner(Owner owner);

    Owner selectOwnidByVid(@Param("vid") Integer vid);

    int updateOwner(Owner owner);

    int deleteOwner(@Param("vid") Integer vid);
}