package com.pengshengtj.dao;

import com.pengshengtj.popj.Owner;
import com.pengshengtj.popj.Vehice;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface VehiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehice
     *
     * @mbg.generated
     */
    int insert(Vehice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehice
     *
     * @mbg.generated
     */
    Vehice selectByPrimaryKey(@Param("vid") Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehice
     *
     * @mbg.generated
     */
    List<Vehice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vehice record);

    /**
     * 查询指定时间内的车辆登记信息
     * @param startTime：开始日期
     * @param endTime：结束日期
     * @return
     */
    List<Vehice> selectByRegtime(@Param("startTime") Date startTime,@Param("endTime") Date endTime);

    List<Vehice> selectByRegtimeAll(@Param("startTime") Date startTime);

    List<Vehice> selectByVid(@Param("vid") List<Integer> vid);

    int insertVehice(Vehice vehice);

    Vehice selectVidByRegtime(@Param("regtime") Date regtime);

    int updateVehice(Vehice vehice);

    List<Vehice> selectByStartTime(@Param("startTime") Date startTime);

}