package com.pengshengtj.popj;

public class Certif {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificates.cerid
     *
     * @mbg.generated
     */
    private Integer cerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column certificates.certype
     *
     * @mbg.generated
     */
    private String certype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificates.cerid
     *
     * @return the value of certificates.cerid
     *
     * @mbg.generated
     */
    public Integer getCerid() {
        return cerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificates.cerid
     *
     * @param cerid the value for certificates.cerid
     *
     * @mbg.generated
     */
    public void setCerid(Integer cerid) {
        this.cerid = cerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column certificates.certype
     *
     * @return the value of certificates.certype
     *
     * @mbg.generated
     */
    public String getCertype() {
        return certype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column certificates.certype
     *
     * @param certype the value for certificates.certype
     *
     * @mbg.generated
     */
    public void setCertype(String certype) {
        this.certype = certype == null ? null : certype.trim();
    }
}