package com.pengshengtj.popj;

public class Client {
    private Integer ownid;
    private String cliname;
    private String cliphone;
    private Integer cerid;
    private String cernum;
    private String cliarea;
    private String clivillage;
    private Integer clifloor;
    private Integer cliunit;
    private Integer clihouse;
    public Integer getOwnid() {
        return ownid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ownid
     *
     * @param ownid the value for client.ownid
     *
     * @mbg.generated
     */
    public void setOwnid(Integer ownid) {
        this.ownid = ownid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cliname
     *
     * @return the value of client.cliname
     *
     * @mbg.generated
     */
    public String getCliname() {
        return cliname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cliname
     *
     * @param cliname the value for client.cliname
     *
     * @mbg.generated
     */
    public void setCliname(String cliname) {
        this.cliname = cliname == null ? null : cliname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cliphone
     *
     * @return the value of client.cliphone
     *
     * @mbg.generated
     */
    public String getCliphone() {
        return cliphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cliphone
     *
     * @param cliphone the value for client.cliphone
     *
     * @mbg.generated
     */
    public void setCliphone(String cliphone) {
        this.cliphone = cliphone == null ? null : cliphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cerid
     *
     * @return the value of client.cerid
     *
     * @mbg.generated
     */
    public Integer getCerid() {
        return cerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cerid
     *
     * @param cerid the value for client.cerid
     *
     * @mbg.generated
     */
    public void setCerid(Integer cerid) {
        this.cerid = cerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cernum
     *
     * @return the value of client.cernum
     *
     * @mbg.generated
     */
    public String getCernum() {
        return cernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cernum
     *
     * @param cernum the value for client.cernum
     *
     * @mbg.generated
     */
    public void setCernum(String cernum) {
        this.cernum = cernum == null ? null : cernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cliarea
     *
     * @return the value of client.cliarea
     *
     * @mbg.generated
     */
    public String getCliarea() {
        return cliarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cliarea
     *
     * @param cliarea the value for client.cliarea
     *
     * @mbg.generated
     */
    public void setCliarea(String cliarea) {
        this.cliarea = cliarea == null ? null : cliarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clivillage
     *
     * @return the value of client.clivillage
     *
     * @mbg.generated
     */
    public String getClivillage() {
        return clivillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clivillage
     *
     * @param clivillage the value for client.clivillage
     *
     * @mbg.generated
     */
    public void setClivillage(String clivillage) {
        this.clivillage = clivillage == null ? null : clivillage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clifloor
     *
     * @return the value of client.clifloor
     *
     * @mbg.generated
     */
    public Integer getClifloor() {
        return clifloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clifloor
     *
     * @param clifloor the value for client.clifloor
     *
     * @mbg.generated
     */
    public void setClifloor(Integer clifloor) {
        this.clifloor = clifloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cliunit
     *
     * @return the value of client.cliunit
     *
     * @mbg.generated
     */
    public Integer getCliunit() {
        return cliunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cliunit
     *
     * @param cliunit the value for client.cliunit
     *
     * @mbg.generated
     */
    public void setCliunit(Integer cliunit) {
        this.cliunit = cliunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clihouse
     *
     * @return the value of client.clihouse
     *
     * @mbg.generated
     */
    public Integer getClihouse() {
        return clihouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clihouse
     *
     * @param clihouse the value for client.clihouse
     *
     * @mbg.generated
     */
    public void setClihouse(Integer clihouse) {
        this.clihouse = clihouse;
    }
}