package com.pengshengtj.popj;

import java.util.Date;

public class Insurance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.insid
     *
     * @mbg.generated
     */
    private Integer insid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.vid
     *
     * @mbg.generated
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.insuretime
     *
     * @mbg.generated
     */
    private Date insuretime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.lefttime
     *
     * @mbg.generated
     */
    private Integer lefttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.frontimg
     *
     * @mbg.generated
     */
    private String frontimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.afterimg
     *
     * @mbg.generated
     */
    private String afterimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.recordimg
     *
     * @mbg.generated
     */
    private String recordimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.cerimg
     *
     * @mbg.generated
     */
    private String cerimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column insurance.labelimg
     *
     * @mbg.generated
     */
    private String labelimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.insid
     *
     * @return the value of insurance.insid
     *
     * @mbg.generated
     */
    public Integer getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.insid
     *
     * @param insid the value for insurance.insid
     *
     * @mbg.generated
     */
    public void setInsid(Integer insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.vid
     *
     * @return the value of insurance.vid
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.vid
     *
     * @param vid the value for insurance.vid
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.insuretime
     *
     * @return the value of insurance.insuretime
     *
     * @mbg.generated
     */
    public Date getInsuretime() {
        return insuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.insuretime
     *
     * @param insuretime the value for insurance.insuretime
     *
     * @mbg.generated
     */
    public void setInsuretime(Date insuretime) {
        this.insuretime = insuretime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.lefttime
     *
     * @return the value of insurance.lefttime
     *
     * @mbg.generated
     */
    public Integer getLefttime() {
        return lefttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.lefttime
     *
     * @param lefttime the value for insurance.lefttime
     *
     * @mbg.generated
     */
    public void setLefttime(Integer lefttime) {
        this.lefttime = lefttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.frontimg
     *
     * @return the value of insurance.frontimg
     *
     * @mbg.generated
     */
    public String getFrontimg() {
        return frontimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.frontimg
     *
     * @param frontimg the value for insurance.frontimg
     *
     * @mbg.generated
     */
    public void setFrontimg(String frontimg) {
        this.frontimg = frontimg == null ? null : frontimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.afterimg
     *
     * @return the value of insurance.afterimg
     *
     * @mbg.generated
     */
    public String getAfterimg() {
        return afterimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.afterimg
     *
     * @param afterimg the value for insurance.afterimg
     *
     * @mbg.generated
     */
    public void setAfterimg(String afterimg) {
        this.afterimg = afterimg == null ? null : afterimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.recordimg
     *
     * @return the value of insurance.recordimg
     *
     * @mbg.generated
     */
    public String getRecordimg() {
        return recordimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.recordimg
     *
     * @param recordimg the value for insurance.recordimg
     *
     * @mbg.generated
     */
    public void setRecordimg(String recordimg) {
        this.recordimg = recordimg == null ? null : recordimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.cerimg
     *
     * @return the value of insurance.cerimg
     *
     * @mbg.generated
     */
    public String getCerimg() {
        return cerimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.cerimg
     *
     * @param cerimg the value for insurance.cerimg
     *
     * @mbg.generated
     */
    public void setCerimg(String cerimg) {
        this.cerimg = cerimg == null ? null : cerimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column insurance.labelimg
     *
     * @return the value of insurance.labelimg
     *
     * @mbg.generated
     */
    public String getLabelimg() {
        return labelimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column insurance.labelimg
     *
     * @param labelimg the value for insurance.labelimg
     *
     * @mbg.generated
     */
    public void setLabelimg(String labelimg) {
        this.labelimg = labelimg == null ? null : labelimg.trim();
    }

    @Override
    public String toString() {
        return "Insurance{" +
                "insid=" + insid +
                ", vid=" + vid +
                ", insuretime=" + insuretime +
                ", lefttime=" + lefttime +
                ", frontimg='" + frontimg + '\'' +
                ", afterimg='" + afterimg + '\'' +
                ", recordimg='" + recordimg + '\'' +
                ", cerimg='" + cerimg + '\'' +
                ", labelimg='" + labelimg + '\'' +
                '}';
    }
}