package com.pengshengtj.popj;

public class Owner {
    private Integer ownid;
    private Integer vid;
    private String ownname;
    private String ownphone;
    private Integer cerid;
    private String cernum;
    private String ownarea;
    private String ownvillage;
    private Integer ownfloor;
    private Integer ownunit;
    private Integer ownhouse;
    public Integer getOwnid() {
        return ownid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownid
     *
     * @param ownid the value for ownertable.ownid
     *
     * @mbg.generated
     */
    public void setOwnid(Integer ownid) {
        this.ownid = ownid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.vid
     *
     * @return the value of ownertable.vid
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.vid
     *
     * @param vid the value for ownertable.vid
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownname
     *
     * @return the value of ownertable.ownname
     *
     * @mbg.generated
     */
    public String getOwnname() {
        return ownname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownname
     *
     * @param ownname the value for ownertable.ownname
     *
     * @mbg.generated
     */
    public void setOwnname(String ownname) {
        this.ownname = ownname == null ? null : ownname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownphone
     *
     * @return the value of ownertable.ownphone
     *
     * @mbg.generated
     */
    public String getOwnphone() {
        return ownphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownphone
     *
     * @param ownphone the value for ownertable.ownphone
     *
     * @mbg.generated
     */
    public void setOwnphone(String ownphone) {
        this.ownphone = ownphone == null ? null : ownphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.cerid
     *
     * @return the value of ownertable.cerid
     *
     * @mbg.generated
     */
    public Integer getCerid() {
        return cerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.cerid
     *
     * @param cerid the value for ownertable.cerid
     *
     * @mbg.generated
     */
    public void setCerid(Integer cerid) {
        this.cerid = cerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.cernum
     *
     * @return the value of ownertable.cernum
     *
     * @mbg.generated
     */
    public String getCernum() {
        return cernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.cernum
     *
     * @param cernum the value for ownertable.cernum
     *
     * @mbg.generated
     */
    public void setCernum(String cernum) {
        this.cernum = cernum == null ? null : cernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownarea
     *
     * @return the value of ownertable.ownarea
     *
     * @mbg.generated
     */
    public String getOwnarea() {
        return ownarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownarea
     *
     * @param ownarea the value for ownertable.ownarea
     *
     * @mbg.generated
     */
    public void setOwnarea(String ownarea) {
        this.ownarea = ownarea == null ? null : ownarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownvillage
     *
     * @return the value of ownertable.ownvillage
     *
     * @mbg.generated
     */
    public String getOwnvillage() {
        return ownvillage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownvillage
     *
     * @param ownvillage the value for ownertable.ownvillage
     *
     * @mbg.generated
     */
    public void setOwnvillage(String ownvillage) {
        this.ownvillage = ownvillage == null ? null : ownvillage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownfloor
     *
     * @return the value of ownertable.ownfloor
     *
     * @mbg.generated
     */
    public Integer getOwnfloor() {
        return ownfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownfloor
     *
     * @param ownfloor the value for ownertable.ownfloor
     *
     * @mbg.generated
     */
    public void setOwnfloor(Integer ownfloor) {
        this.ownfloor = ownfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownunit
     *
     * @return the value of ownertable.ownunit
     *
     * @mbg.generated
     */
    public Integer getOwnunit() {
        return ownunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownunit
     *
     * @param ownunit the value for ownertable.ownunit
     *
     * @mbg.generated
     */
    public void setOwnunit(Integer ownunit) {
        this.ownunit = ownunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ownertable.ownhouse
     *
     * @return the value of ownertable.ownhouse
     *
     * @mbg.generated
     */
    public Integer getOwnhouse() {
        return ownhouse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ownertable.ownhouse
     *
     * @param ownhouse the value for ownertable.ownhouse
     *
     * @mbg.generated
     */
    public void setOwnhouse(Integer ownhouse) {
        this.ownhouse = ownhouse;
    }

    @Override
    public String toString() {
        return "Owner{" +
                "ownid=" + ownid +
                ", vid=" + vid +
                ", ownname='" + ownname + '\'' +
                ", ownphone='" + ownphone + '\'' +
                ", cerid=" + cerid +
                ", cernum='" + cernum + '\'' +
                ", ownarea='" + ownarea + '\'' +
                ", ownvillage='" + ownvillage + '\'' +
                ", ownfloor=" + ownfloor +
                ", ownunit=" + ownunit +
                ", ownhouse=" + ownhouse +
                '}';
    }
}