package com.pengshengtj.popj;

import java.util.Date;

public class Vehice {
    private Integer vid;
    private String vcolor;
    private String vbrand;
    private Date vbuytime;
    private String platenum;
    private String theftnum;
    private String framenum;
    private String motornum;
    private Date regtime;
    private Integer isinsurance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.vid
     *
     * @return the value of vehice.vid
     *
     * @mbg.generated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.vid
     *
     * @param vid the value for vehice.vid
     *
     * @mbg.generated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.vcolor
     *
     * @return the value of vehice.vcolor
     *
     * @mbg.generated
     */
    public String getVcolor() {
        return vcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.vcolor
     *
     * @param vcolor the value for vehice.vcolor
     *
     * @mbg.generated
     */
    public void setVcolor(String vcolor) {
        this.vcolor = vcolor == null ? null : vcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.vbrand
     *
     * @return the value of vehice.vbrand
     *
     * @mbg.generated
     */
    public String getVbrand() {
        return vbrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.vbrand
     *
     * @param vbrand the value for vehice.vbrand
     *
     * @mbg.generated
     */
    public void setVbrand(String vbrand) {
        this.vbrand = vbrand == null ? null : vbrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.vbuytime
     *
     * @return the value of vehice.vbuytime
     *
     * @mbg.generated
     */
    public Date getVbuytime() {
        return vbuytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.vbuytime
     *
     * @param vbuytime the value for vehice.vbuytime
     *
     * @mbg.generated
     */
    public void setVbuytime(Date vbuytime) {
        this.vbuytime = vbuytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.platenum
     *
     * @return the value of vehice.platenum
     *
     * @mbg.generated
     */
    public String getPlatenum() {
        return platenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.platenum
     *
     * @param platenum the value for vehice.platenum
     *
     * @mbg.generated
     */
    public void setPlatenum(String platenum) {
        this.platenum = platenum == null ? null : platenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.theftnum
     *
     * @return the value of vehice.theftnum
     *
     * @mbg.generated
     */
    public String getTheftnum() {
        return theftnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.theftnum
     *
     * @param theftnum the value for vehice.theftnum
     *
     * @mbg.generated
     */
    public void setTheftnum(String theftnum) {
        this.theftnum = theftnum == null ? null : theftnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.framenum
     *
     * @return the value of vehice.framenum
     *
     * @mbg.generated
     */
    public String getFramenum() {
        return framenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.framenum
     *
     * @param framenum the value for vehice.framenum
     *
     * @mbg.generated
     */
    public void setFramenum(String framenum) {
        this.framenum = framenum == null ? null : framenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.motornum
     *
     * @return the value of vehice.motornum
     *
     * @mbg.generated
     */
    public String getMotornum() {
        return motornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.motornum
     *
     * @param motornum the value for vehice.motornum
     *
     * @mbg.generated
     */
    public void setMotornum(String motornum) {
        this.motornum = motornum == null ? null : motornum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.regtime
     *
     * @return the value of vehice.regtime
     *
     * @mbg.generated
     */
    public Date getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.regtime
     *
     * @param regtime the value for vehice.regtime
     *
     * @mbg.generated
     */
    public void setRegtime(Date regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehice.isinsurance
     *
     * @return the value of vehice.isinsurance
     *
     * @mbg.generated
     */
    public Integer getIsinsurance() {
        return isinsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehice.isinsurance
     *
     * @param isinsurance the value for vehice.isinsurance
     *
     * @mbg.generated
     */
    public void setIsinsurance(Integer isinsurance) {
        this.isinsurance = isinsurance;
    }

    @Override
    public String toString() {
        return "Vehice{" +
                "vid=" + vid +
                ", vcolor='" + vcolor + '\'' +
                ", vbrand='" + vbrand + '\'' +
                ", vbuytime=" + vbuytime +
                ", platenum='" + platenum + '\'' +
                ", theftnum='" + theftnum + '\'' +
                ", framenum='" + framenum + '\'' +
                ", motornum='" + motornum + '\'' +
                ", regtime=" + regtime +
                ", isinsurance=" + isinsurance +
                '}';
    }
}